spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'FALSE'
#        format_sql: 'TRUE' beshe na true
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${db_password}
    username: ${db_username}
    url: jdbc:mysql://${db_address}:3306/bassheads_bg?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    initialization-mode: always
  kafka:
    bootstrap-servers: localhost:9092
    groupId: test
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer


logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
#        SQL: DEBUG
        SQL:
      nodeValue: WARN
    blog: WARN

server:
  port: 8080
